const CACHE_NAME = "ludus-scaccorum-static-9f199e39ddde";

const CORE_ASSETS = [
  "./",
  "./index.html",
  "./styles.css?v=9f199e39ddde",
  "./css/system.css?v=9f199e39ddde",
  "./css/shell.css?v=9f199e39ddde",
  "./css/board.css?v=9f199e39ddde",
  "./css/coach.css?v=9f199e39ddde",
  "./css/home.css?v=9f199e39ddde",
  "./css/classics.css?v=9f199e39ddde",
  "./css/notebook.css?v=9f199e39ddde",
  "./css/progress.css?v=9f199e39ddde",
  "./css/museum.css?v=9f199e39ddde",
  "./css/settings.css?v=9f199e39ddde",
  "./css/account.css?v=9f199e39ddde",
  "./config.js?v=9f199e39ddde",
  "./js/ludus.js?v=9f199e39ddde",
  "./js/chess.js?v=9f199e39ddde",
  "./js/pgn.js?v=9f199e39ddde",
  "./js/engine.js?v=9f199e39ddde",
  "./js/scoring.js?v=9f199e39ddde",
  "./js/insights.js?v=9f199e39ddde",
  "./js/concepts.js?v=9f199e39ddde",
  "./js/settings.js?v=9f199e39ddde",
  "./js/profile.js?v=9f199e39ddde",
  "./js/facts.js?v=9f199e39ddde",
  "./js/reader.js?v=9f199e39ddde",
  "./js/audio.js?v=9f199e39ddde",
  "./js/auth.js?v=9f199e39ddde",
  "./js/classics.js?v=9f199e39ddde",
  "./js/ui/kit.js?v=9f199e39ddde",
  "./js/ui/shell.js?v=9f199e39ddde",
  "./js/ui/board.js?v=9f199e39ddde",
  "./js/ui/coach.js?v=9f199e39ddde",
  "./js/ui/home.js?v=9f199e39ddde",
  "./js/ui/classics.js?v=9f199e39ddde",
  "./js/ui/notebook.js?v=9f199e39ddde",
  "./js/ui/progress.js?v=9f199e39ddde",
  "./js/ui/museum.js?v=9f199e39ddde",
  "./js/ui/settings.js?v=9f199e39ddde",
  "./js/ui/account.js?v=9f199e39ddde",
  "./app.js?v=9f199e39ddde",
  "./manifest.json",
  "./assets/icons/icon-192.png",
  "./assets/icons/icon-512.png",
  "./assets/icons/icon-maskable-512.png",
  "./assets/icons/apple-touch-icon.png",
  "./assets/brand/logo.svg",
  "./assets/brand/favicon.svg",
  "./assets/fonts/inter-latin-wght.woff2",
  "./assets/fonts/cormorant-latin-wght.woff2",
  "./assets/landing/maestro.webp",
  "./assets/pieces/cburnett/bB.svg",
  "./assets/pieces/cburnett/bK.svg",
  "./assets/pieces/cburnett/bN.svg",
  "./assets/pieces/cburnett/bP.svg",
  "./assets/pieces/cburnett/bQ.svg",
  "./assets/pieces/cburnett/bR.svg",
  "./assets/pieces/cburnett/wB.svg",
  "./assets/pieces/cburnett/wK.svg",
  "./assets/pieces/cburnett/wN.svg",
  "./assets/pieces/cburnett/wP.svg",
  "./assets/pieces/cburnett/wQ.svg",
  "./assets/pieces/cburnett/wR.svg",
];

// The list above is generated by scripts/generate-version.js: every local
// script and stylesheet index.html loads, versioned with the content hash, plus
// the static assets. Do not edit the JS/CSS entries by hand.
//
// The engine is deliberately absent from the list above: it is 7.3 MB and is
// only needed once somebody actually plays. The same goes for lazily loaded
// data (js/data/*.js, fetched with ?v=<version> by Ludus.util.loadScript). The
// fetch handler below stores any successful same-origin GET the first time it
// is requested, so those files are there offline from then on.

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(CORE_ASSETS))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys
        .filter((key) => key !== CACHE_NAME)
        .map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

function sameOriginGet(request) {
  if (request.method !== "GET") return false;
  const url = new URL(request.url);
  return url.origin === self.location.origin;
}

function navigationFallback(request) {
  return fetch(request).catch(() => caches.match("./index.html"));
}

function cacheFirst(request) {
  return caches.match(request)
    .then((cached) => {
      if (cached) return cached;
      return fetch(request).then((response) => {
        if (response && response.ok) {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
        }
        return response;
      });
    })
    .catch(() => caches.match(request, { ignoreSearch: true }));
}

self.addEventListener("fetch", (event) => {
  if (!sameOriginGet(event.request)) return;
  if (event.request.mode === "navigate") {
    event.respondWith(navigationFallback(event.request));
    return;
  }
  event.respondWith(cacheFirst(event.request));
});
